name: Build

on:
  workflow_call:

jobs:
  build-push-custom-registry:
    environment: PROD
    strategy:
      matrix:
        include:
        - target: app_php
          image_var: NEW_IMAGE_NAME_PHP
        - target: app_caddy
          image_var: NEW_IMAGE_NAME_CADDY
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v13
      with:
        IMAGE_NAME: ${{ vars[matrix.image_var] }}
        BUILD_CONTEXT: .
        BUILD_TARGET: ${{ matrix.target }}
        REGISTRY_JSON_KEY: ${{ secrets.REGISTRY_PASSWORD }}
        IMAGE_REPOSITORY: ${{ vars.REGISTRY_NAME }}
        TAGS: |
          type=raw,value=prod-{{sha}},enable=${{ github.ref_type == 'tag' }}
          type=raw,value=nonprod-{{sha}},enable=${{ github.event_name != 'pull_request' && github.ref_type != 'tag' }}
          type=sha,enable=${{ github.event_name == 'pull_request' }}
